const RADAR_DADOS = {
  "geradoEm": "2026-09-17T15:11:38",
  "noticias": [
    {
      "id": "222b7164033dafb3",
      "titulo": "Governo de MT suspende notícias institucionais do Portal em cumprimento às normas eleitorais Veja Mais",
      "resumo": "Governo de MT suspende notícias institucionais do Portal em cumprimento às normas eleitorais Veja Mais",
      "link": "https://www5.sefaz.mt.gov.br/web/mt/w/governo-de-mt-suspende-not%C3%ADcias-institucionais-do-portal-em-cumprimento-%C3%A0s-normas-eleitorais",
      "fonte": "SEFAZ MT",
      "esfera": "estadual",
      "uf": "MT",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:46",
      "primeira_vez_em": "2026-09-17T15:10:46"
    },
    {
      "id": "8b919b7384234279",
      "titulo": "Consulta de Notas Fiscais",
      "resumo": "Consulta de Notas Fiscais",
      "link": "https://sefaz.es.gov.br/consultanota",
      "fonte": "SEFAZ ES",
      "esfera": "estadual",
      "uf": "ES",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:41",
      "primeira_vez_em": "2026-09-17T15:10:41"
    },
    {
      "id": "6cff987543c8c065",
      "titulo": "DAE para pagamento de IPVA - boleto",
      "resumo": "DAE para pagamento de IPVA - boleto",
      "link": "https://servicos.ce.gov.br/catalogo-de-servicos/2426",
      "fonte": "SEFAZ CE",
      "esfera": "estadual",
      "uf": "CE",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:38",
      "primeira_vez_em": "2026-09-17T15:10:38"
    },
    {
      "id": "5eea618ca2cc84eb",
      "titulo": "Certidão negativa de débitos estaduais",
      "resumo": "Certidão negativa de débitos estaduais",
      "link": "https://servicos.ce.gov.br/catalogo-de-servicos/2409",
      "fonte": "SEFAZ CE",
      "esfera": "estadual",
      "uf": "CE",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:38",
      "primeira_vez_em": "2026-09-17T15:10:38"
    },
    {
      "id": "72c6f05e4579827b",
      "titulo": "Certidão de quitação de IPVA",
      "resumo": "Certidão de quitação de IPVA",
      "link": "https://servicos.ce.gov.br/catalogo-de-servicos/899",
      "fonte": "SEFAZ CE",
      "esfera": "estadual",
      "uf": "CE",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:38",
      "primeira_vez_em": "2026-09-17T15:10:38"
    },
    {
      "id": "2000dd301177a7b7",
      "titulo": "8 dúvidas mais comuns sobre a união estável",
      "resumo": "A união estável ainda causa uma série de dúvidas entre os casais. Esclareça tudo na leitura a seguir",
      "link": "https://jornalcontabil.com.br/noticia/8-duvidas-mais-comuns-sobre-a-uniao-estavel/",
      "fonte": "Jornal Contábil",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "Thu, 17 Sep 2026 17:42:24 +0000",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:26",
      "primeira_vez_em": "2026-09-17T15:10:26"
    },
    {
      "id": "8a6cf9ff974b763a",
      "titulo": "Atestado médico ou odontológico: dentista pode te afastar do trabalho?",
      "resumo": "Entenda o que a lei diz sobre a validade do documento emitido por cirurgiões-dentistas e veja como ele funciona no dia a dia.",
      "link": "https://jornalcontabil.com.br/noticia/atestado-medico-ou-odontologico-dentista-pode-te-afastar-do-trabalho/",
      "fonte": "Jornal Contábil",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "Thu, 17 Sep 2026 16:26:03 +0000",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:26",
      "primeira_vez_em": "2026-09-17T15:10:26"
    },
    {
      "id": "01fc1ced115a1f88",
      "titulo": "Malha fina: passo a passo para acertar as contas com o fisco sem erros",
      "resumo": "Veja como checar pendências, evitar novos erros e resolver a situação com a Receita Federal sem estresse",
      "link": "https://jornalcontabil.com.br/noticia/malha-fina-passo-a-passo-para-acertar-as-contas-com-o-fisco-sem-erros/",
      "fonte": "Jornal Contábil",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "Thu, 17 Sep 2026 15:26:40 +0000",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:26",
      "primeira_vez_em": "2026-09-17T15:10:26"
    },
    {
      "id": "add5e3211f788d39",
      "titulo": "Como Consultar CNPJ Negativado Antes de Vender a Prazo (Guia para Credores)",
      "resumo": "Vender a prazo ou fechar um contrato com uma empresa que já está com o nome sujo é um dos jeitos mais comuns de uma PME ver o caixa travar. Antes de aprovar crédito, emitir um boleto parcelado ou assinar um contrato de prestação de serviço continuada, existe uma checagem simples e gratuita que evita […]",
      "link": "https://jornalcontabil.com.br/noticia/consultar-cnpj-negativado/",
      "fonte": "Jornal Contábil",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "Thu, 17 Sep 2026 13:21:50 +0000",
      "impacto": "médio",
      "tags": [
        "Prazo/Obrigação"
      ],
      "coletado_em": "2026-09-17T15:10:26",
      "primeira_vez_em": "2026-09-17T15:10:26"
    },
    {
      "id": "59f18a3b109140df",
      "titulo": "Evite multas! Últimos dias para o envio da DITR 2026",
      "resumo": "A multa para quem perder o prazo é de 1% ao mês ou fração de atraso sobre o imposto devido",
      "link": "https://jornalcontabil.com.br/noticia/evite-multas-ultimos-dias-para-o-envio-da-ditr-2026/",
      "fonte": "Jornal Contábil",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "Thu, 17 Sep 2026 12:19:41 +0000",
      "impacto": "alto",
      "tags": [
        "Prazo/Obrigação",
        "Multa/Penalidade"
      ],
      "coletado_em": "2026-09-17T15:10:26",
      "primeira_vez_em": "2026-09-17T15:10:26"
    },
    {
      "id": "e88b4feaab400314",
      "titulo": "DTTA 2026: documento obrigatório deve ser entregue até dia 30",
      "resumo": "Essa obrigação é um documento legal que formaliza a transferência de propriedade de ações de uma pessoa para outra",
      "link": "https://jornalcontabil.com.br/noticia/dtta-2026-documento-obrigatorio-deve-ser-entregue-ate-dia-30/",
      "fonte": "Jornal Contábil",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "Thu, 17 Sep 2026 12:05:08 +0000",
      "impacto": "alto",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:26",
      "primeira_vez_em": "2026-09-17T15:10:26"
    },
    {
      "id": "07af53545ad6a955",
      "titulo": "Nota Técnica 2026.009 v.1.00 - Publicada em 09/09/2026",
      "resumo": "Divulga correção em regra de validação",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=ADlgg2xjMZI=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "e38892674e142a10",
      "titulo": "Nota Técnica 2026.002 v.1.10a - Publicada em 25/08/2026",
      "resumo": "Operações de vendas presenciais e não presenciais com impressão do DANFE Simplificado Tipo 2",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=8zOzIahvn8I=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [
        "NFe",
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "81db86e8434c0e4f",
      "titulo": "Nota Técnica 2026.006 v.1.00 - Publicada em 25/08/2026",
      "resumo": "Divulga especificação técnica para vinculação entre NF-e e transação financeira sujeita ao split payment",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=k7zG06n5M6I=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [
        "NFe",
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "e2a50ae8eccfe1a8",
      "titulo": "Nota Técnica 2014.001 v.1.41 - Publicada em 04/08/2026",
      "resumo": "Divulga especificação técnica para emissão do Evento Prévio de Emissão em Contingência (EPEC)",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=9hgG  cH8gA=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "e4937f762f128a36",
      "titulo": "Nota Técnica 2026.007 v.1.00 - Publicada em 04/08/2026",
      "resumo": "Regras de validação e atualiza regras existentes da NF-e/NFC-e para verificação dos cadastros na Lista Centralizada de Contribuintes da RFB (LCC-RFB) e no Cadastro Centralizado de Contribuintes (CCC).",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=jVEAeMhv83w=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [
        "NFe",
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "c79576affbd403f5",
      "titulo": "Nota Técnica 2025.002 v.1.51 - Publicada em 04/08/2026",
      "resumo": "Nota técnica de adequação dos leiautes da NF-e e da NFC-e para inclusão dos campos e das regras de validação referentes à Reforma Tributária do Consumo - RTC",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=AKD/muSmiIY=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "alto",
      "tags": [
        "Reforma Tributária",
        "NFe",
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "7f41fe5f1640b502",
      "titulo": "Nota Técnica 2026.001 v.1.02b - Publicada em 31/07/2026",
      "resumo": "Especifica o Provedor de Assinatura e Autorização (PAA) no âmbito da NF-e.",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=AlgHfV6gpAU=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [
        "NFe",
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "0859ec432b231549",
      "titulo": "Nota Técnica 2023.003 v.1.30 - Publicada em 29/07/2026",
      "resumo": "Alteração de regras de validação.",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=NjyiPKZOBFU=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "8640ac9406476bfb",
      "titulo": "Nota Técnica 2014.002 - v.1.40 - Publicada em 03/07/2026",
      "resumo": "Web Service de distribuição de documentos fiscais eletrônicos.",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=uWO2d/gTuWg=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "b4d2823b992dc0cb",
      "titulo": "Nota Técnica 2026.004 v.1.01 - Publicada em 08/06/2026",
      "resumo": "Atualização do schema da NF-e/NFC-e para adequação ao CNPJ alfanumérico",
      "link": "https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=BTZQzgsO9Ws=",
      "fonte": "NF-e - Notas Técnicas",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "",
      "impacto": "médio",
      "tags": [
        "NFe",
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:19",
      "primeira_vez_em": "2026-09-17T15:10:19"
    },
    {
      "id": "37f8c90ecf5bc3e6",
      "titulo": "Senado leva ao ComPública debate sobre combate à desinformação",
      "resumo": "O 4º Congresso Brasileiro de Comunicação Pública (ComPública) reúne, até sexta-feira (18), comunicadores, pesquisadores, estudantes e especialistas de todo o país para discutir o papel e os desafios da comunicação pública. Com o tema “Uma agenda para a cidadania”, o encontro é realizado na Câmara dos Deputados e aborda assuntos como integridade da informação, políticas públicas, direitos, redes sociais, linguagem simples, inteligência artificial e participação cidadã. Na abertura, a diretora da Secretaria de Comunicação do Senado (Secom), Glauciene Lara, destacou a importância do congresso para aproximar pesquisa, formulação de políticas e prática profissional. — Este evento é um espaço privilegiado de discussão de alto nível, que reúne quem pesquisa, quem formula políticas, quem ensina e quem faz comunicação pública todos os dias. Um evento que realmente alinha a teoria e a prática, um espaço para construir respostas coletivas a problemas que nenhuma instituição vai conseguir enfrentar sozinha — afirmou. Comunicação pública Segundo o presidente da Associação Brasileira de Comunicação Pública (ABCPública), Jorge Duarte, o congresso recebeu mais de 1,6 mil inscrições de todos os estados. A programação inclui minicursos, mesas de debate e apresentações de 160 trabalhos distribuídos em seis grupos temáticos. Entre os assuntos discutidos estão democracia, transparência, governança digital, regulação da comunicação e combate à desinformação. A abertura também contou com representantes da Câmara dos Deputados, do Tribunal de Contas da União (TCU), da Universidade de Brasília (UnB) e da Organização das Nações Unidas (ONU). A Secom participa ainda de atividades sobre integridade da informação, gestão e regulação da comunicação e combate à desinformação. A programação inclui a apresentação de trabalhos sobre o Senado Verifica e sobre a gestão da reputação institucional do Senado.",
      "link": "https://www12.senado.leg.br/noticias/materias/2026/09/17/senado-leva-ao-compublica-debate-sobre-combate-a-desinformacao",
      "fonte": "Senado Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-09-17T16:12:03Z",
      "impacto": "baixo",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:18",
      "primeira_vez_em": "2026-09-17T15:10:18"
    },
    {
      "id": "1c268d4352b9c4d5",
      "titulo": "Sancionada Política Nacional de Minerais Críticos e Estratégicos",
      "resumo": "Com uma das maiores reservas de terras-raras do mundo, o Brasil passou a ter uma Política Nacional de Minerais Críticos e Estratégicos (PNMCE). A norma foi sancionada e publicada em edição extra do Diário Oficial da União (DOU) de quarta-feira (16). Entre os objetivos da política estão o desenvolvimento da cadeia produtiva desses minerais, a agregação de valor em território nacional e a garantia da soberania e do interesse nacional. A política nacional, instituída pela Lei 15.506, de 2026, abrange pesquisa, extração, beneficiamento, transformação mineral e mineração urbana, que é a recuperação de minerais e metais presentes em resíduos e produtos descartados, como celulares, computadores, baterias e outros equipamentos, para que possam ser reaproveitados. Entre os instrumentos previstos estão o Fundo Garantidor da Atividade Mineral (FGAM), com participação da União de até R$ 2 bilhões, e o Programa Federal de Beneficiamento e Transformação de Minerais Críticos e Estratégicos (PFMCE). O programa poderá conceder créditos fiscais de até R$ 1 bilhão por ano entre 2030 e 2034 para empresas que realizem beneficiamento, transformação mineral e mineração urbana no país. A matéria foi aprovada no Senado no início de setembro, após tramitar como PL 2.780/2024, de autoria do deputado Zé Silva (Solidariedade-MG). No Senado, o projeto foi relatado pelo senador Eduardo Braga (MDB-AM). O texto também institui o Conselho Nacional para Industrialização de Minerais Críticos e Estratégicos (Cimce), vinculado à Presidência da República, responsável por coordenar, planejar e acompanhar a execução da PNMCE. Minerais Considerados essenciais para a produção de carros elétricos, smartphones, data centers e sistemas militares, entre outros, os minerais críticos e estratégicos têm definições diferentes na norma. A lei estabelece como minerais críticos os recursos minerais necessários a setores-chave da economia nacional cuja disponibilidade seja insuficiente em razão da baixa produção interna e cuja escassez possa representar risco à transição energética, à segurança alimentar ou à soberania nacional. Já os minerais estratégicos são recursos relevantes para o país em razão de reservas significativas e essenciais para a geração de superávit na balança comercial, o desenvolvimento tecnológico e regional ou a redução das emissões de gases de efeito estufa (GEEs). As empresas que participarem dos programas previstos na política deverão cumprir requisitos definidos em lei, que incluem investimentos em pesquisa, desenvolvimento e inovação e contrapartidas socioambientais.",
      "link": "https://www12.senado.leg.br/noticias/materias/2026/09/17/sancionada-politica-nacional-de-minerais-criticos-e-estrategicos",
      "fonte": "Senado Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-09-17T13:23:31Z",
      "impacto": "alto",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:18",
      "primeira_vez_em": "2026-09-17T15:10:18"
    },
    {
      "id": "af194bf2b56c3194",
      "titulo": "Eleições 2026: saiba a ordem dos votos na urna eletrônica",
      "resumo": "Nas eleições gerais de 4 de outubro, os eleitores registrarão seis escolhas na urna eletrônica: pela ordem, deputado federal, deputado estadual (distrital, apenas no caso do Distrito Federal), dois senadores, governador e presidente da República. A votação ocorrerá das 8h às 17h (horário de Brasília), sendo garantido o direito de votar a quem estiver na fila no momento do encerramento. A jornada na cabine individual tem início logo após a identificação oficial do eleitor, realizada pela mesa receptora mediante apresentação do título eleitoral ou do aplicativo e-Título, ou um documento oficial com foto. Serão aceitos carteira de identidade (RG), identidade social, passaporte ou outro documento de valor legal equivalente, carteira de categoria profissional reconhecida por lei, certificado de reservista, carteira de trabalho e carteira nacional de habilitação. A sequência de votação é determinada pelo Tribunal Superior Eleitoral (TSE) e apresentada automaticamente pela urna eletrônica. A ordem inicia-se com o voto para deputado federal (quatro dígitos) e prossegue para deputado estadual ou distrital (cinco dígitos). Em seguida, o eleitor deve digitar os números para as duas vagas em disputa para o Senado Federal (três dígitos cada). O processo é finalizado com as escolhas para governador (dois dígitos) e presidente da República (dois dígitos). Após a digitação de cada número, a tela exibe a foto, o nome completo, o cargo e o partido do candidato. Desde o pleito de 2022, o equipamento conta com uma pausa de segurança: a tecla “Confirma” permanece inativa por um segundo enquanto é exibida a mensagem “Confira seu voto”. O mecanismo foi desenvolvido para evitar confirmações precipitadas e permitir a verificação atenta dos dados do candidato. Tecla verde Se a tecla verde for pressionada durante esse intervalo de segurança, o comando será ignorado pelo sistema, bastando ao eleitor acioná-la novamente após o destravamento. O TSE esclarece que não é necessário aguardar por nenhuma mensagem adicional de confirmação, devendo o cidadão aproveitar a breve pausa apenas para conferir a imagem e os dados exibidos na tela. Para facilitar o processo e reduzir o tempo de permanência na cabine, a Justiça Eleitoral recomenda que o eleitor leve uma anotação em papel — a tradicional \"cola eleitoral\" — com os números dos candidatos organizados na ordem exata da votação. O TSE destaca que dados históricos de eleições anteriores servem apenas como referência, uma vez que a duração do procedimento varia de acordo com cada cidadão. A votação é encerrada assim que a última confirmação é registrada para o cargo de presidente da República. Ao final do horário regulamentar, a urna eletrônica emite o Boletim de Urna (BU), documento público impresso que detalha o total de votos registrados na seção e assegura a transparência e a auditabilidade do processo eleitoral.",
      "link": "https://www12.senado.leg.br/noticias/materias/2026/09/16/eleicoes-2026-saiba-a-ordem-dos-votos-na-urna-eletronica",
      "fonte": "Senado Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-09-16T19:35:26Z",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:18",
      "primeira_vez_em": "2026-09-17T15:10:18"
    },
    {
      "id": "dfb0c109feed7af3",
      "titulo": "Lei facilita corte de impostos para data centers e programas contra câncer",
      "resumo": "Em 2026, os parlamentares poderão deixar de cumprir certas regras fiscais ao proporem ou analisarem projetos que concedem benefícios tributários para data centers, programas de apoio a pessoas com câncer e com deficiência, áreas de livre comércio da Região Norte e resseguradoras brasileiras. É o que prevê a Lei Complementar 237, sancionada na terça-feira (15) pela Presidência da República, com um veto, e publicada no Diário Oficial da União. Entre as regras dispensadas para as propostas que reduzem tributos, estão: criação de metas para o incentivo fiscal; avaliação de seu custo-benefício; limite em 2% do PIB. Várias dessas exigências haviam sido criadas em 2025 para frear o avanço de renúncias fiscais (cortes de impostos) e outras vantagens específicas para certos setores. A nova lei tem origem no Projeto de Lei Complementar (PLP) 74/2026, relatado no Senado pelo senador Camilo Santana (PT-CE). No relatório, Camilo diz que a medida é necessária para o “atendimento de demandas setoriais legítimas”. Ele lembra que tais incentivos fiscais devem estar previstos no Orçamento e que serão considerados para a meta do resultado primário — cálculo que monitora a saúde das contas públicas. Regras dispensadas Ao analisar os incentivos, os parlamentares poderão desconsiderar a vedação de ampliar isenções fiscais (prevista na Lei de Diretrizes Orçamentárias de 2026) e o limite de 2% do PIB para o total de benefícios tributários federais. Para 2026, o teto equivale a cerca de R$ 274,2 bi, segundo cálculo de 2025 do Planalto. Os senadores e deputados também ficam dispensados de: estimar o impacto orçamentário-financeiro; reavaliar a receita prevista na lei orçamentária; prever a arrecadação do mesmo valor de outra forma, como compensação; estimar a quantidade de beneficiários, entre outras normas. A maior parte das restrições flexibilizadas estavam previstas na Lei Complementar 224, de 2025, que determinou um corte linear de 10% em benefícios fiscais federais. Ela é fruto de discussões encabeçadas pelo Executivo para rever os valores que deixa de arrecadar. Em 2025, a Receita Federal projetou que os incentivos fiscais poderiam chegar a R$ 612,8 bilhões em 2026. Beneficiadas A norma viabiliza o Regime Especial de Tributação para Serviços de Datacenter (Redata), sancionado nesta quarta-feira (16) para estimular a instalação desses estabelecimentos no país, principalmente os que tenham como foco a computação em nuvem e a inteligência artificial (IA). Os data centers (locais que guardam os sistemas de computação de uma empresa) são considerados estratégicos e cada vez mais demandados no mundo, segundo especialistas ouvidos no Senado. As novas regras também abarcam os seguintes incentivos fiscais: do Programa Nacional de Apoio à Atenção Oncológica (Pronon) e do Programa Nacional de Apoio à Atenção da Saúde da Pessoa com Deficiência (Pronas/PCD). Criados em 2012, os programas permitem deduzir doações do Imposto de Renda; às empresas habilitadas nas áreas de livre comércio, atualmente localizadas no Acre, Amapá, Amazonas, Rondônia e Roraima. Com menos impostos, o regime tributário busca impulsionar a economia de cidades fronteiriças; às resseguradoras locais (sediadas no Brasil), com relação à desoneração de Imposto sobre a Renda das Pessoas Jurídicas e da Contribuição Social sobre o Lucro Líquido. A resseguradora é uma empresa que funciona como “seguro das seguradoras”, assumindo parte dos riscos de seus negócios. Veto O governo federal vetou trecho que livrava municípios de até 65 mil habitantes de comprovar que não havia atraso nas suas dívidas com a União para receber transferências voluntárias de recursos federais. Atualmente 90,5% dos 5.570 municípios se enquadrariam na regra, segundo estimativa de julho do IBGE. Para o Planalto, a medida desincentivaria a boa gestão dos recursos públicos.",
      "link": "https://www12.senado.leg.br/noticias/materias/2026/09/16/lei-facilita-corte-de-impostos-para-data-centers-e-programas-contra-cancer",
      "fonte": "Senado Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-09-16T18:08:42Z",
      "impacto": "alto",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:18",
      "primeira_vez_em": "2026-09-17T15:10:18"
    },
    {
      "id": "ee530ea67fd9b4ad",
      "titulo": "Sancionado o fim da 'taxa das blusinhas'",
      "resumo": "Sancionado o fim da 'taxa das blusinhas'",
      "link": "https://www12.senado.leg.br/noticias/infomaterias/2026/09/sancionado-o-fim-da-taxa-das-blusinhas",
      "fonte": "Senado Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-09-16T16:59:38Z",
      "impacto": "alto",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:18",
      "primeira_vez_em": "2026-09-17T15:10:18"
    },
    {
      "id": "fc84fdaa19d314e1",
      "titulo": "Urna eletrônica: veja como funciona e como o voto é protegido",
      "resumo": "A urna eletrônica é utilizada nas eleições brasileiras desde 1996. Ao longo de 30 anos, o sistema eletrônico de votação passou por aperfeiçoamentos e ganhou mecanismos de fiscalização e auditoria antes, durante e depois da votação. Segundo o Tribunal Superior Eleitoral (TSE), não há registro comprovado de fraude nos processos de coleta dos votos, apuração e totalização desde a implantação da urna eletrônica. A segurança do sistema não depende de um único mecanismo. A Justiça Eleitoral oferece mais de 40 processos de auditoria ao longo do ciclo eleitoral, com participação de partidos políticos, Ministério Público, Ordem dos Advogados do Brasil (OAB), Congresso Nacional e outras instituições que fiscalizam o processo eleitoral. Entre os procedimentos estão a abertura dos códigos-fonte, o teste público de segurança, a assinatura digital dos sistemas, a lacração dos programas, a verificação de autenticidade e integridade das urnas e a conferência dos resultados após a votação. Como os sistemas são preparados e fiscalizados Antes das eleições, os sistemas utilizados na votação passam por etapas de inspeção, testes e fiscalização. Na cerimônia de assinatura digital e lacração, os programas são apresentados às instituições que participam da fiscalização. Depois de compilados, recebem códigos de verificação, os chamados hashes, e assinaturas digitais. Os sistemas são então gravados em mídias e lacrados para serem utilizados nas urnas. A assinatura digital permite verificar matematicamente a autenticidade e a integridade de um arquivo. Com isso, a Justiça Eleitoral consegue verificar se os sistemas utilizados nas urnas correspondem àqueles que passaram pelos procedimentos oficiais. O código-fonte dos sistemas eleitorais também fica disponível para inspeção das instituições fiscalizadoras durante o período definido pela Justiça Eleitoral. Além disso, especialistas podem participar do teste público de segurança, realizado para identificar eventuais vulnerabilidades e corrigi-las antes das eleições. Cada urna também possui mecanismos próprios de segurança para a identificação dos equipamentos e dos resultados produzidos. Segundo o secretário de Tecnologia da Informação do TSE, Júlio Valente, cada urna conta com chaves criptográficas próprias, utilizadas para assinar digitalmente os resultados registrados pelo equipamento. A urna não é conectada à internet Durante a votação, a urna funciona de forma isolada e não é conectada à internet, ao Wi-Fi ou ao Bluetooth. O equipamento não possui componentes de hardware ou software destinados a esse tipo de conexão. O TSE informa que a urna funciona off-line e executa apenas programas previamente inspecionados. Ao final da votação, a urna imprime o Boletim de Urna (BU) e grava os dados do resultado em uma mídia. A partir daí, as informações seguem para os sistemas de totalização por uma rede utilizada exclusivamente pela Justiça Eleitoral. — A urna é isolada, não tem internet, não tem Wi-Fi, não tem Bluetooth. Depois que termina a votação, a gente retira a mídia de resultado e faz a transmissão dos resultados — explicou Valente, em entrevista à TV Senado. Falta de energia A urna possui bateria própria e pode continuar funcionando em caso de interrupção do fornecimento de energia elétrica. Em locais de difícil acesso, a Justiça Eleitoral também prevê alternativas para garantir o funcionamento dos equipamentos. Identificação do eleitor A eleitora ou o eleitor apresenta documento ao mesário, que faz a habilitação para a votação. Quando disponível, a biometria pode ser utilizada para confirmar a identidade. Se a identificação biométrica não for reconhecida, existem procedimentos previstos pela Justiça Eleitoral para permitir a votação após as verificações necessárias. Boletim Ao final da votação, é impresso o Boletim de Urna (BU), que registra os resultados daquela seção eleitoral. Os dados da seção são transmitidos para os sistemas de totalização, e os boletins são disponibilizados pela Justiça Eleitoral para consulta. A urna também mantém o Registro Digital do Voto (RDV), no qual os votos são registrados individualmente. O registro, segundo Valente, permite refazer o processo de contagem dos votos e pode ser utilizado em procedimentos de auditoria e recontagem, quando necessário. A fiscalização também permite verificar a autenticidade e a integridade dos sistemas, conferir os arquivos produzidos pela urna e comparar os resultados registrados no boletim com os dados utilizados na totalização. Testes de integridade O Teste de Integridade das Urnas Eletrônicas simula uma votação em ambiente controlado. Votos previamente preenchidos em cédulas de papel são digitados na urna, e o resultado produzido pelo equipamento é comparado com os votos registrados manualmente. O objetivo é verificar se a urna registra e contabiliza os votos corretamente. O Teste de Integridade também tem uma modalidade com biometria. Nela, eleitoras e eleitores voluntários participam da habilitação da urna de teste por meio da biometria. O procedimento é realizado em locais próximos às seções eleitorais e passou a integrar as auditorias da votação a partir das eleições de 2024. Urna eletrônica no Senado Em agosto, o Senado recebeu a exposição O Caminho do Voto – a jornada da democracia, que apresenta etapas do processo eleitoral, desde o desenvolvimento e os testes da urna eletrônica até a votação e a apuração dos resultados. A mostra foi inaugurada pelos presidentes do TSE, Kássio Nunes Marques, e do Senado, Davi Alcolumbre. Durante a cerimônia, Nunes Marques destacou a atuação coordenada dos órgãos envolvidos no processo eleitoral para garantir transparência e fiscalização. — Que cada visitante, ao percorrer esta exposição, possa compreender que o verdadeiro caminho do voto tem origem no trabalho coordenado das instituições da República, no compromisso permanente com a transparência e na responsabilidade compartilhada de preservar a confiança da sociedade no processo eleitoral brasileiro — ressaltou. Davi afirmou que a exposição também contribui para divulgar o funcionamento do sistema eletrônico de votação. — Temos um dos processos eleitorais mais confiáveis do mundo, se não for o mais confiável. Precisamos disseminar entre as brasileiras e os brasileiros esta convicção, esta certeza — ressaltou.",
      "link": "https://www12.senado.leg.br/noticias/materias/2026/09/16/urna-eletronica-veja-como-funciona-e-como-o-voto-e-protegido",
      "fonte": "Senado Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-09-16T14:28:32Z",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:18",
      "primeira_vez_em": "2026-09-17T15:10:18"
    },
    {
      "id": "5a9a86e73556d59c",
      "titulo": "Política nacional de conscientização e orientação sobre LAM agora é lei",
      "resumo": "A Política Nacional de Conscientização e Orientação sobre a Linfangioleiomiomatose (LAM) foi sancionada pela Presidência da República. A Lei 15.505, de 2026, publicada em edição extraordinária do Diário Oficial da União (DOU) na terça-feira (15), prevê ações no Sistema Único de Saúde (SUS) para ampliar o acesso ao diagnóstico e ao tratamento da doença. A LAM é uma doença rara que acomete principalmente mulheres jovens, entre a puberdade e a menopausa. Provoca a formação de cistos nos pulmões, o que pode levar à perda progressiva da capacidade respiratória. A doença pode ainda comprometer os rins e o sistema linfático. Estima-se que entre mil e 2 mil pessoas sejam afetadas pela LAM no Brasil. A nova lei prevê ações para orientar profissionais de saúde sobre os sintomas e o diagnóstico da LAM, além da criação de centros de referência para diagnóstico, tratamento e acompanhamento de pacientes. Também estabelece a implantação de um sistema nacional para coleta e processamento de dados sobre os casos de LAM e determina que o SUS garanta aos pacientes acesso aos meios disponíveis para tratamento e controle da doença. Em agosto, a Comissão de Direitos Humanos (CDH), presidida por Damares, promoveu audiência pública sobre o tema. Segundo os participantes, o diagnóstico tardio e a dificuldade de acesso aos locais de tratamento estão entre os principais obstáculos enfrentados pelas pessoas com LAM. A medida tem origem no PL 5.238/2025, apresentado pelo senador Alan Rick (Republicanos-AC) quando era deputado. No Senado, a proposta foi aprovada pela Comissão de Assuntos Sociais (CAS), em decisão terminativa, após receber parecer favorável da senadora Damares Alves (Republicanos-DF).",
      "link": "https://www12.senado.leg.br/noticias/materias/2026/09/16/politica-nacional-de-conscientizacao-e-orientacao-sobre-lam-agora-e-lei",
      "fonte": "Senado Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-09-16T14:10:44Z",
      "impacto": "alto",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:18",
      "primeira_vez_em": "2026-09-17T15:10:18"
    },
    {
      "id": "7ec70af6910740c7",
      "titulo": "Na China, Brasil avança em parceria estratégica em mercados de carbono e realiza agendas bilaterais com parceiros",
      "resumo": "Na abertura de conferência chinesa de mercados de carbono para lideranças globais em Wuhan, Ministério da Fazenda defende alinhamento entre regulação, financiamento e combate às desigualdades",
      "link": "https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/setembro/na-china-brasil-avanca-em-parceria-estrategica-em-mercados-de-carbono-e-realiza-agendas-bilaterais-com-parceiros",
      "fonte": "Ministério da Fazenda",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "16/09/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:15",
      "primeira_vez_em": "2026-09-17T15:10:15"
    },
    {
      "id": "1b96acf232589fdb",
      "titulo": "Regime Especial de Tributação para Serviços de Datacenter é sancionado",
      "resumo": "Novo regime prevê incentivos fiscais para a instalação de data centers no Brasil e faz parte de um conjunto de ações da economia de baixo carbono",
      "link": "https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/setembro/regime-especial-de-tributacao-para-servicos-de-datacenter-e-sancionado",
      "fonte": "Ministério da Fazenda",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "16/09/2026",
      "impacto": "alto",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:15",
      "primeira_vez_em": "2026-09-17T15:10:15"
    },
    {
      "id": "a9a22f90ca007b05",
      "titulo": "Receita Federal indica oportunidade de regularização de créditos de PIS/Pasep e Cofins",
      "resumo": "Inconsistências de R$1,3 bilhão podem ser corrigidas até 10 de novembro",
      "link": "https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/setembro/receita-federal-indica-oportunidade-de-regularizacao-de-creditos-de-pis-pasep-e-cofins",
      "fonte": "Ministério da Fazenda",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "15/09/2026",
      "impacto": "médio",
      "tags": [
        "PIS/COFINS"
      ],
      "coletado_em": "2026-09-17T15:10:15",
      "primeira_vez_em": "2026-09-17T15:10:15"
    },
    {
      "id": "f588dd789c07c54b",
      "titulo": "Encontro em Fortaleza debateu como viabilizar projetos de biometano no Nordeste",
      "resumo": "Workshop foi promovido pelo Ministério da Fazenda e pelo Banco do Nordeste",
      "link": "https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/encontro-em-fortaleza-debateu-como-viabilizar-projetos-de-biometano-no-nordeste",
      "fonte": "Ministério da Fazenda",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "15/09/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:15",
      "primeira_vez_em": "2026-09-17T15:10:15"
    },
    {
      "id": "ff0cb63d2006d0cd",
      "titulo": "SPA publica portaria de enfrentamento ao mercado ilegal de apostas",
      "resumo": "Norma amplia os procedimentos destinados à prevenção, à identificação e à repressão de transações de pagamento relacionadas à exploração irregular de apostas de quota fixa",
      "link": "https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/setembro/spa-publica-portaria-de-enfrentamento-ao-mercado-ilegal-de-apostas",
      "fonte": "Ministério da Fazenda",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "15/09/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:15",
      "primeira_vez_em": "2026-09-17T15:10:15"
    },
    {
      "id": "24dbd0a0f36aa8e4",
      "titulo": "Mercado projeta déficit primário de R$ 52,271 bilhões para o Governo Central em 2026, mostra Prisma Fiscal",
      "resumo": "Mediana das projeções recuou de R$ 59,145 bilhões em agosto para R$ 52,271 bilhões em setembro",
      "link": "https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/setembro/mercado-projeta-deficit-primario-de-r-52-271-bilhoes-para-o-governo-central-em-2026-mostra-prisma-fiscal",
      "fonte": "Ministério da Fazenda",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "15/09/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:15",
      "primeira_vez_em": "2026-09-17T15:10:15"
    },
    {
      "id": "26e3feab1234de20",
      "titulo": "Tesouro honra em agosto R$ 79,95 milhões em dívidas garantidas pela União",
      "resumo": "Desde 2016, a União pagou R$ 89,66 bilhões para honrar garantias em operações de crédito de estados e municípios",
      "link": "https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/setembro/tesouro-honra-em-agosto-r-79-95-milhoes-em-dividas-garantidas-pela-uniao",
      "fonte": "Ministério da Fazenda",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "15/09/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:15",
      "primeira_vez_em": "2026-09-17T15:10:15"
    },
    {
      "id": "3488f63f8f381fc4",
      "titulo": "Coalizão Aberta aprova plano de trabalho e define estrutura de Secretariado na China",
      "resumo": "Em reunião em Wuhan, Brasil, China e União Europeia e mais 8 países fecham acordo para acelerar a convergência de mercados regulados de carbono nacionais",
      "link": "https://www.gov.br/fazenda/pt-br/assuntos/noticias/2026/setembro/coalizao-aberta-aprova-plano-de-trabalho-e-define-estrutura-de-secretariado-na-china",
      "fonte": "Ministério da Fazenda",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "14/09/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:15",
      "primeira_vez_em": "2026-09-17T15:10:15"
    },
    {
      "id": "4baf6d16f5f6d474",
      "titulo": "Novo acesso ao Regularize para representantes de empresas",
      "resumo": "Responsáveis por PJ já podem acessar serviços diretamente do Regularize por meio da conta gov.br",
      "link": "https://www.gov.br/pgfn/pt-br/assuntos/noticias/2026/novo-acesso-ao-regularize-para-representantes-de-empresas",
      "fonte": "PGFN",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "17/09/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:14",
      "primeira_vez_em": "2026-09-17T15:10:14"
    },
    {
      "id": "8af9031daf5b35f0",
      "titulo": "Operação Bomba Oculta visa postos de combustíveis clandestinos",
      "resumo": "Ação é desdobramento da Operação Carbono Oculto e conta com colaboração entre PGFN e diversas instituições",
      "link": "https://www.gov.br/pgfn/pt-br/assuntos/noticias/2026/operacao-bomba-oculta-visa-postos-de-combustiveis-clandestinos",
      "fonte": "PGFN",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "28/08/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:14",
      "primeira_vez_em": "2026-09-17T15:10:14"
    },
    {
      "id": "96e91c67f56c632d",
      "titulo": "Seleção Nacional de Estagiários",
      "resumo": "Inscrições são gratuitas e vão de 20 de agosto a 3 de setembro",
      "link": "https://www.gov.br/pgfn/pt-br/assuntos/noticias/2026/selecao-nacional-de-estagiarios",
      "fonte": "PGFN",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "19/08/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:14",
      "primeira_vez_em": "2026-09-17T15:10:14"
    },
    {
      "id": "34948173140ec564",
      "titulo": "Informamos que não haverá atendimento nas unidades da PGFN em todo o Brasil, na terça-feira, 11 de agosto.",
      "resumo": "Informamos que não haverá atendimento nas unidades da PGFN em todo o Brasil, na terça-feira, 11 de agosto.",
      "link": "https://www.gov.br/pgfn/pt-br/assuntos/noticias/2026/informamos-que-nao-havera-atendimento-na-terca-feira-11-de-agosto",
      "fonte": "PGFN",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "07/08/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:14",
      "primeira_vez_em": "2026-09-17T15:10:14"
    },
    {
      "id": "8bd7518c825c9b11",
      "titulo": "Defeso Eleitoral 2026",
      "resumo": "Links importantes que continuam ativos",
      "link": "https://www.gov.br/pgfn/pt-br/assuntos/noticias/2026/defeso-eleitoral-2026",
      "fonte": "PGFN",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "09/07/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:14",
      "primeira_vez_em": "2026-09-17T15:10:14"
    },
    {
      "id": "2b0c4bb2793ed187",
      "titulo": "Novos editais de transação da PGFN estão disponíveis",
      "resumo": "Contribuintes podem regularizar situação fiscal, inclusive no âmbito do Programa Desenrola Rural",
      "link": "https://www.gov.br/pgfn/pt-br/assuntos/noticias/2026/novos-editais-de-transacao-da-pgfn-estao-disponiveis",
      "fonte": "PGFN",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "22/06/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:14",
      "primeira_vez_em": "2026-09-17T15:10:14"
    },
    {
      "id": "b081958b5f7506fe",
      "titulo": "Publicado o Perguntas e Respostas da NFS-e",
      "resumo": "O material foi compilado com base nas dúvidas recebidas de Municípios, contribuintes e empresas de desenvolvimento",
      "link": "https://www.gov.br/nfse/pt-br/noticias/publicado-o-perguntas-e-respostas-da-nfs-e",
      "fonte": "NFS-e Nacional (CGNFS-e)",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "16/09/2026",
      "impacto": "médio",
      "tags": [
        "NFSe"
      ],
      "coletado_em": "2026-09-17T15:10:13",
      "primeira_vez_em": "2026-09-17T15:10:13"
    },
    {
      "id": "b329be74653055a3",
      "titulo": "Secretaria Executiva do CGNFS-e participa de homologação de novas funcionalidades da Nota Fiscal de Serviço Eletrônica para a Reforma Tributária",
      "resumo": "Atividades aconteceram na sede do Serpro em Belo Horizonte (MG)",
      "link": "https://www.gov.br/nfse/pt-br/noticias/secretaria-executiva-do-cgnfs-e-participa-de-homologacao-de-novas-funcionalidades-da-nota-fiscal-de-servico-eletronica-para-a-reforma-tributaria",
      "fonte": "NFS-e Nacional (CGNFS-e)",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "05/09/2026",
      "impacto": "alto",
      "tags": [
        "Reforma Tributária",
        "NFSe"
      ],
      "coletado_em": "2026-09-17T15:10:13",
      "primeira_vez_em": "2026-09-17T15:10:13"
    },
    {
      "id": "46f050b2bd9a044c",
      "titulo": "Comitê Gestor do Simples Nacional prorroga a obrigatoriedade de emissão de notas fiscais de serviço pelo Emissor Nacional da NFS-e",
      "resumo": "Comitê Gestor do Simples Nacional prorroga a obrigatoriedade de emissão de notas fiscais de serviço pelo Emissor Nacional da NFS-e",
      "link": "https://www.gov.br/nfse/pt-br/noticias/comite-gestor-do-simples-nacional-prorroga-a-obrigatoriedade-de-emissao-de-notas-fiscais-de-servico-pelo-emissor-nacional-da-nfs-e",
      "fonte": "NFS-e Nacional (CGNFS-e)",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "11/08/2026",
      "impacto": "alto",
      "tags": [
        "NFSe",
        "Simples Nacional",
        "Prazo/Obrigação"
      ],
      "coletado_em": "2026-09-17T15:10:13",
      "primeira_vez_em": "2026-09-17T15:10:13"
    },
    {
      "id": "b9c9daabd31b6e3e",
      "titulo": "CGNFS-e orienta sobre os prazos para destaque de IBS/CBS nas notas fiscais de serviço",
      "resumo": "Comitê Gestor do IBS e Receita Federal flexibilizaram a obrigatoriedade de informações nos documentos fiscais. Regras de validação que exigem informações do IBS e da CBS foram alteradas para evitar rejeição de documentos fiscais.",
      "link": "https://www.gov.br/nfse/pt-br/noticias/cgnfs-e-orienta-sobre-os-prazos-para%20destaque-de-ibs-cbs-nas-notas-fiscais-de-servico",
      "fonte": "NFS-e Nacional (CGNFS-e)",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "07/08/2026",
      "impacto": "alto",
      "tags": [
        "IBS",
        "CBS",
        "NFSe",
        "Prazo/Obrigação"
      ],
      "coletado_em": "2026-09-17T15:10:13",
      "primeira_vez_em": "2026-09-17T15:10:13"
    },
    {
      "id": "8ad9456dba6ac974",
      "titulo": "Plataforma NFS-e disponibiliza novas evoluções em Produção Restrita e divulga cronograma de implantação",
      "resumo": "Entre as evoluções estão o CNPJ Alfanumérico e os grupos IBS/CBS no Emissor Web",
      "link": "https://www.gov.br/nfse/pt-br/noticias/plataforma-nfs-e-disponibiliza-novas-evolucoes-em-producao-restrita-e-divulga-cronograma-de-implantacao",
      "fonte": "NFS-e Nacional (CGNFS-e)",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "28/07/2026",
      "impacto": "alto",
      "tags": [
        "IBS",
        "CBS",
        "NFSe"
      ],
      "coletado_em": "2026-09-17T15:10:13",
      "primeira_vez_em": "2026-09-17T15:10:13"
    },
    {
      "id": "0b7a31ff3defd6f2",
      "titulo": "Manutenção no ambiente do CNPJ neste sábado (25) não afetará os principais serviços da NFS-e",
      "resumo": "Apenas os serviços de criação de usuário e recuperação de senha do Portal do Contribuinte serão afetados",
      "link": "https://www.gov.br/nfse/pt-br/noticias/manutencao-no-ambiente-do-cnpj-neste-sabado-25-nao-afetara-os-principais-servicos-da-nfs-e",
      "fonte": "NFS-e Nacional (CGNFS-e)",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "23/07/2026",
      "impacto": "médio",
      "tags": [
        "NFSe"
      ],
      "coletado_em": "2026-09-17T15:10:13",
      "primeira_vez_em": "2026-09-17T15:10:13"
    },
    {
      "id": "d448d576b31f4e14",
      "titulo": "DANFSE: novos ajustes e prorrogação do prazo para adequação",
      "resumo": "Novo prazo passa a ser 3 de agosto de 2026",
      "link": "https://www.gov.br/nfse/pt-br/noticias/danfse-novos-ajustes-de-leiaute-e-prorrogacao-do-prazo-para-adequacao",
      "fonte": "NFS-e Nacional (CGNFS-e)",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "14/07/2026",
      "impacto": "médio",
      "tags": [
        "NFSe",
        "Prazo/Obrigação"
      ],
      "coletado_em": "2026-09-17T15:10:13",
      "primeira_vez_em": "2026-09-17T15:10:13"
    },
    {
      "id": "990de00c70b0bcde",
      "titulo": "NFS-e Via: Publicada nova API para consulta de alíquotas do ISS",
      "resumo": "As Administrações Municipais poderão consultar alíquotas de ISS por trecho e data",
      "link": "https://www.gov.br/nfse/pt-br/noticias/nfs-e-via-publicada-nova-api-para-consulta-de-aliquotas-do-iss",
      "fonte": "NFS-e Nacional (CGNFS-e)",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "10/07/2026",
      "impacto": "médio",
      "tags": [
        "ISS",
        "NFSe",
        "API/Sistemas Gov"
      ],
      "coletado_em": "2026-09-17T15:10:13",
      "primeira_vez_em": "2026-09-17T15:10:13"
    },
    {
      "id": "08398f1e2c89c97b",
      "titulo": "Receita Federal disponibilizará a versão web da DITR 2026",
      "resumo": "Serviço permite preencher, transmitir, retificar e consultar a Declaração do Imposto sobre a Propriedade Territorial Rural de forma on-line.",
      "link": "https://www.gov.br/receitafederal/pt-br/assuntos/noticias/receita-federal-disponibilizara-a-versao-web-da-ditr-2026",
      "fonte": "Receita Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-07-22T16:51:56Z",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:12",
      "primeira_vez_em": "2026-09-17T15:10:12"
    },
    {
      "id": "246d24ac1d0cd774",
      "titulo": "Receita Federal informa parada programada do Sistema de Leilão Eletrônico",
      "resumo": "Serviço ficará indisponível no dia 23 de julho de 2026, das 6h às 16h, para implantação do CNPJ Alfanumérico",
      "link": "https://www.gov.br/receitafederal/pt-br/assuntos/noticias/receita-federal-informa-parada-programada-do-sistema-de-leilao-eletronico",
      "fonte": "Receita Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-07-20T19:54:16Z",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:12",
      "primeira_vez_em": "2026-09-17T15:10:12"
    },
    {
      "id": "2de55424d6f704af",
      "titulo": "Emissão do CNPJ e de documentos fiscais por pessoas físicas contribuintes da CBS começará em 1º de janeiro de 2027",
      "resumo": "Decreto prorroga para 2027 a obrigatoriedade de inscrição no CNPJ e de emissão de documentos fiscais por pessoas físicas contribuintes da CBS, ampliando o prazo de adaptação à Reforma Tributária.",
      "link": "https://www.gov.br/receitafederal/pt-br/assuntos/noticias/emissao-do-cnpj-e-de-documentos-fiscais-por-pessoas-fisicas-contribuintes-da-cbs-comecara-em-1o-de-janeiro-de-2027",
      "fonte": "Receita Federal",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "2026-07-22T17:02:38Z",
      "impacto": "alto",
      "tags": [
        "Reforma Tributária",
        "CBS",
        "Prazo/Obrigação"
      ],
      "coletado_em": "2026-09-17T15:10:12",
      "primeira_vez_em": "2026-09-17T15:10:12"
    },
    {
      "id": "5a2a272341f6a971",
      "titulo": "CNPJ Alfanumérico: operação normal",
      "resumo": "Publicado por Coordenação Técnica do ENCAT",
      "link": "https://dfe-portal.svrs.rs.gov.br/Cff/Avisos/2982",
      "fonte": "Conformidade Fácil (ENCAT/SVRS) - Avisos",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "23/07/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:11",
      "primeira_vez_em": "2026-09-17T15:10:11"
    },
    {
      "id": "1ca5429d7569b551",
      "titulo": "ATENÇÃO: CNPJ de Teste para Alfanumérico (Novidade: Adicionados NFe e e NFCe)",
      "resumo": "Publicado por SEFAZ Virtual RS",
      "link": "https://dfe-portal.svrs.rs.gov.br/Cff/Avisos/2978",
      "fonte": "Conformidade Fácil (ENCAT/SVRS) - Avisos",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "29/05/2026",
      "impacto": "médio",
      "tags": [
        "NFe",
        "API/Sistemas Gov"
      ],
      "coletado_em": "2026-09-17T15:10:11",
      "primeira_vez_em": "2026-09-17T15:10:11"
    },
    {
      "id": "73b214f6161b9cb9",
      "titulo": "Implantação no ambiente de produção da versão 1.13 da NT da Reforma Tributária",
      "resumo": "Publicado por SVRS",
      "link": "https://dfe-portal.svrs.rs.gov.br/Cff/Avisos/2974",
      "fonte": "Conformidade Fácil (ENCAT/SVRS) - Avisos",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "03/03/2026",
      "impacto": "alto",
      "tags": [
        "Reforma Tributária",
        "NT (Nota Técnica)"
      ],
      "coletado_em": "2026-09-17T15:10:11",
      "primeira_vez_em": "2026-09-17T15:10:11"
    },
    {
      "id": "607173e000fc3989",
      "titulo": "Novidade: Link para o MOC Online",
      "resumo": "Publicado por Coordenação Técnica do ENCAT",
      "link": "https://dfe-portal.svrs.rs.gov.br/Cff/Noticias/3007",
      "fonte": "Conformidade Fácil (ENCAT/SVRS) - Avisos",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "10/09/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:11",
      "primeira_vez_em": "2026-09-17T15:10:11"
    },
    {
      "id": "a9b85ebff2d35b2f",
      "titulo": "Implantadas NTs 2026.002 em PRODUÇÃO na SVRS",
      "resumo": "Publicado por SEFAZ Virtual RS",
      "link": "https://dfe-portal.svrs.rs.gov.br/Cff/Noticias/3005",
      "fonte": "Conformidade Fácil (ENCAT/SVRS) - Avisos",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "31/08/2026",
      "impacto": "médio",
      "tags": [
        "API/Sistemas Gov"
      ],
      "coletado_em": "2026-09-17T15:10:11",
      "primeira_vez_em": "2026-09-17T15:10:11"
    },
    {
      "id": "74129502b829908e",
      "titulo": "Implantada a regra de validação de exigencia de IBS e CBS no ambiente de homologação",
      "resumo": "Publicado por SEFAZ Virtual RS",
      "link": "https://dfe-portal.svrs.rs.gov.br/Cff/Noticias/2981",
      "fonte": "Conformidade Fácil (ENCAT/SVRS) - Avisos",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "06/07/2026",
      "impacto": "alto",
      "tags": [
        "IBS",
        "CBS",
        "API/Sistemas Gov"
      ],
      "coletado_em": "2026-09-17T15:10:11",
      "primeira_vez_em": "2026-09-17T15:10:11"
    },
    {
      "id": "e5fc5ae97dc8d1c2",
      "titulo": "Lei Complementar 227 de 13 de Janeiro de 2026",
      "resumo": "Publicado por Ajustes SINIEF",
      "link": "http://www.in.gov.br/web/dou/-/lei-complementar-n-227-de-13-de-janeiro-de-2026-681157850",
      "fonte": "Conformidade Fácil (ENCAT/SVRS) - Avisos",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "14/01/2026",
      "impacto": "médio",
      "tags": [],
      "coletado_em": "2026-09-17T15:10:11",
      "primeira_vez_em": "2026-09-17T15:10:11"
    },
    {
      "id": "07591671a87026e9",
      "titulo": "ATO CONJUNTO RFB/CGIBS Nº 1, DE 22 DE DEZEMBRO DE 2025",
      "resumo": "Publicado por Ato Conjunto RFB/CGIBS",
      "link": "https://www.in.gov.br/web/dou/-/ato-conjunto-rfb/cgibs-n-1-de-22-de-dezembro-de-2025-677624586",
      "fonte": "Conformidade Fácil (ENCAT/SVRS) - Avisos",
      "esfera": "federal",
      "uf": "",
      "data_publicacao": "23/12/2025",
      "impacto": "alto",
      "tags": [
        "IBS"
      ],
      "coletado_em": "2026-09-17T15:10:11",
      "primeira_vez_em": "2026-09-17T15:10:11"
    }
  ],
  "reforma": {
    "_comentario": "Placar da Reforma Tributaria exibido no painel. Isso NAO e calculado automaticamente pelo scraper (evita numero errado/inventado). Atualize manualmente o campo percentual e etapa_atual quando sair uma noticia oficial confirmando um novo marco (ex: nova LC sancionada, novo cronograma no Confaz/Receita). O scraper so avisa no terminal quando encontra noticias com palavras-chave de CBS/IBS/Imposto Seletivo, para vc lembrar de revisar este arquivo.",
    "atualizado_em": "2026-09-17",
    "itens": [
      {
        "id": "ibs",
        "nome": "IBS",
        "descricao": "Imposto sobre Bens e Serviços (estados e municípios)",
        "percentual": 35,
        "etapa_atual": "Fase de teste 2026 (alíquota simbólica) — regulamentação e sistemas em implantação",
        "cor": "azul"
      },
      {
        "id": "cbs",
        "nome": "CBS",
        "descricao": "Contribuição sobre Bens e Serviços (federal)",
        "percentual": 40,
        "etapa_atual": "Fase de teste 2026 (alíquota simbólica) — apuração assistida em desenvolvimento",
        "cor": "roxo"
      },
      {
        "id": "imposto-seletivo",
        "nome": "Imposto Seletivo",
        "descricao": "Tributo sobre produtos prejudiciais à saúde/meio ambiente",
        "percentual": 15,
        "etapa_atual": "Regulamentação em andamento — cobrança prevista a partir de 2027",
        "cor": "verde"
      }
    ]
  }
};
